.circleci/config.yml, app/frontend/src/cljs/teet/navigation/navigation_style.cljs, app/frontend/src/cljs/teet/project/project_style.cljs, app/frontend/src/cljs/teet/theme/theme_colors.cljs, app/frontend/src/cljs/teet/theme/theme_panels.cljs, app/frontend/src/cljs/teet/theme/theme_provider.cljs, app/frontend/src/cljs/teet/ui/progress.cljs
This is just a test to see if CircleCI build is run on the PR.
=> Make small change to test if tests are run on PRs

app/backend/resources/schema.edn, app/backend/src/clj/teet/admin/admin_commands.clj, app/backend/src/clj/teet/admin/admin_queries.clj, app/backend/src/clj/teet/db_api/db_api_handlers.clj, app/backend/src/clj/teet/environment.clj, app/backend/src/clj/teet/login/login_api_token.clj, app/backend/src/clj/teet/login/login_commands.clj, app/common/src/cljc/teet/user/user_roles.cljc, app/frontend/resources/routes.edn, app/frontend/src/cljs/teet/admin/admin_controller.cljs, app/frontend/src/cljs/teet/admin/admin_view.cljs, app/frontend/src/cljs/teet/common/common_controller.cljs, app/frontend/src/cljs/teet/login/login_controller.cljs, app/frontend/src/cljs/teet/main.cljs, app/frontend/src/cljs/teet/navigation/navigation_view.cljs, app/frontend/src/cljs/teet/route_macros.clj, app/frontend/src/cljs/teet/ui/material_ui.cljs, app/frontend/src/cljs/teet/user/user_controller.cljs
Added:
- user information to Datomic schema.
- new admin section
- role checks
=> Access rights mgmt

app/common/src/cljc/teet/project/project_model.cljc, app/frontend/src/cljs/teet/theme/theme_provider.cljs, app/frontend/src/cljs/teet/ui/stepper.cljs
Disabled buttons in the project view stepper until production lifecycle is more thoroughly thought out.
=> Teet 344 block construction

app/backend/resources/schema.edn, app/backend/src/clj/teet/project/project_commands.clj, app/frontend/resources/public/language/en.edn, app/frontend/resources/public/language/et.edn, app/frontend/src/cljs/teet/activity/activity_controller.cljs, app/frontend/src/cljs/teet/activity/activity_view.cljs, app/frontend/src/cljs/teet/common/common_controller.cljs, app/frontend/src/cljs/teet/project/project_controller.cljs, app/frontend/src/cljs/teet/project/project_view.cljs, app/frontend/src/cljs/teet/ui/stepper.cljs
https://jira.mkm.ee/browse/TEET-345
Activity names should now check for valid lifecycle type.
=> Teet 345 activity names

app/backend/src/clj/teet/meta/meta_model.clj, app/backend/src/clj/teet/project/project_commands.clj, app/frontend/resources/public/language/en.edn, app/frontend/resources/public/language/et.edn, app/frontend/src/cljs/teet/project/project_controller.cljs, app/frontend/src/cljs/teet/project/project_layers.cljs, app/frontend/src/cljs/teet/project/project_setup_view.cljs, app/frontend/src/cljs/teet/project/project_style.cljs, app/frontend/src/cljs/teet/project/project_view.cljs, app/frontend/src/cljs/teet/theme/itemlist_styles.cljs, app/frontend/src/cljs/teet/ui/itemlist.cljs
Added functionality to edit related features.
Some parts will still be quite messy since all the showing of lists were heavily bundled with the setup wizard
=> Teet 339 select related entities

app/frontend/src/cljs/teet/map/map_features.cljs
If a feature is small (based on feature area and current resolution), show an extra indicator icon style for it.
=> TEET-354 Show extra indicator circle for small features

app/backend/src/clj/teet/db_api/core.clj, app/frontend/resources/public/language/en.edn, app/frontend/resources/public/language/et.edn, app/frontend/resources/routes.edn, app/frontend/src/cljs/teet/common/common_controller.cljs, app/frontend/src/cljs/teet/main.cljs, app/frontend/src/cljs/teet/ui/unauthorized.cljs
Fixes issue where users that don't have access to a resource end up in a permanent login loop.
=> Teet 382 unauthorized resource

app/backend/src/clj/teet/project/project_queries.clj, app/common/src/cljc/teet/project/activity_model.cljc, app/common/src/cljc/teet/project/project_model.cljc, app/frontend/src/cljs/teet/projects/projects_view.cljs, app/frontend/src/cljs/teet/ui/stepper.cljs
Adds project status to project listing query.
=> Teet 422 project status

app/common/src/clj/teet/comment/comment_model.cljc, app/frontend/src/cljs/teet/file/file_view.cljs, app/frontend/src/cljs/teet/main.cljs, app/frontend/src/cljs/teet/route_macros.clj, app/frontend/src/cljs/teet/ui/context.cljs, app/frontend/src/cljs/teet/ui/url.cljs
Don't use a global atom for navigation info.
Pass navigation via React context.
=> Navigation context

app/backend/README.md, app/backend/deps.edn, app/backend/src/clj/teet/environment.clj, app/backend/src/clj/user.clj, app/backend/test/teet/system_test.clj, app/backend/test/teet/test/utils.clj
This PR adds an MVP version of DB tests.
=> Add minimal setup for db tests

app/backend/resources/schema.edn, app/backend/src/clj/teet/meta/meta_model.clj, app/backend/src/clj/teet/project/project_commands.clj, app/common/src/cljc/teet/project/project_model.cljc, app/frontend/src/cljs/teet/project/project_controller.cljs, app/frontend/src/cljs/teet/project/project_setup_view.cljs, app/frontend/src/cljs/teet/project/project_view.cljs, app/frontend/src/cljs/teet/ui/tabs.cljs
Remove the project setup wizard.
=> TEET-450 wizardectomy

app/common/src/cljc/teet/project/project_specs.cljc, app/frontend/resources/public/language/en.edn, app/frontend/resources/public/language/et.edn, app/frontend/src/cljs/teet/ui/date_picker.cljs, app/frontend/src/cljs/teet/ui/form.cljs
Fix form validations when using multi-attribute fields.
Refactor form code to remove duplication.
=> Form validation and refactoring

app/backend/dev-src/user.clj, app/backend/src/clj/teet/integration/x_road.clj
Now provides much more complete information.
=> TEET 531, improve part 3 / part 4 parsing from property register responses

app/frontend/src/cljs/teet/project/land_controller.cljs, app/frontend/src/cljs/teet/project/land_view.cljs
It's not functionally complete yet because of some WIP functionality in the land view (process status and maybe also impact data in data model), but I think it's a good time to merge to avoid merge conflicts.
=> TEET-514 - Cadastral unit filtering for land view 

app/backend/src/clj/teet/admin/admin_commands.clj, app/backend/src/clj/teet/permission/permission_db.clj, app/backend/src/clj/teet/project/project_commands.clj, app/backend/src/clj/teet/user/user_db.clj, app/backend/test/teet/activity_commands_test.clj, app/backend/test/teet/admin/admin_commands_test.clj, app/backend/test/teet/comment_commands_test.clj, app/backend/test/teet/project/project_commands_test.clj, app/backend/test/teet/test/utils.clj, app/common/src/cljc/teet/file/file_model.cljc, app/common/src/cljc/teet/file/file_spec.cljc, app/common/src/cljc/teet/user/user_model.cljc, app/common/src/cljc/teet/user/user_spec.cljc, app/frontend/src/cljs/teet/project/project_view.cljs
https://jira.mkm.ee/browse/TEET-688
=> TEET-688 Don't allow adding of a role that the user already has

app/backend/restore-test.bash, app/backend/src/clj/teet/backup/backup_ion.clj
The test is a mix of shell and inline clojure now, could be ported to proper test code later, but we don't have time allocated to do it now so let's check it in to git meanwhile.
Also includes error handling fixes from the old backup-error-handling branch that semeed to have gotten lost in the merge before with the file uuids etc.
=> Backup/restore itest + error handling fixes

app/backend/resources/schema.edn, app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/migration/file_sequence_number.clj, app/backend/test/teet/file/filename_metadata_test.clj, app/common/src/cljc/teet/file/filename_metadata.cljc, app/common/src/cljc/teet/util/string.cljc
Added new metadata fields for file names
=> TEET-897 file metadata

app/backend/resources/datomic/ion-config.edn, app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/link/link_commands.clj, app/backend/src/clj/teet/link/link_db.clj, app/backend/src/clj/teet/link/link_queries.clj, app/backend/src/clj/teet/meeting/meeting_commands.clj, app/common/src/cljc/teet/link/link_model.cljc, app/frontend/src/cljs/teet/file/file_style.cljs, app/frontend/src/cljs/teet/file/file_view.cljs, app/frontend/src/cljs/teet/link/link_view.cljs
Allow linking of existing files in the same project.
=> TEET-660 link project files

app/backend/resources/schema.edn, app/backend/src/clj/teet/comment/comment_commands.clj, app/backend/src/clj/teet/comment/comment_db.clj, app/backend/src/clj/teet/meeting/meeting_queries.clj, app/backend/src/clj/teet/notification/notification_queries.clj, app/backend/src/clj/teet/project/project_db.clj, app/common/src/cljc/teet/comment/comment_model.cljc, app/frontend/src/cljs/teet/comments/comments_controller.cljs, app/frontend/src/cljs/teet/meeting/meeting_view.cljs, app/frontend/src/cljs/teet/task/task_view.cljs, app/frontend/src/cljs/teet/ui/tabs.cljs
=> TEET-929 meeting comments

app/backend/dev-src/user.clj, app/backend/resources/schema.edn, app/common/src/cljc/teet/cooperation/cooperation_model.cljc
Add new schema entries for cooperation section.
=> TEET-1053 cooperation schema

app/backend/src/clj/teet/file/file_commands.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/file/file_controller.cljs, app/frontend/src/cljs/teet/file/file_view.cljs
=> Teet 1013 replace file

app/backend/src/clj/teet/cooperation/cooperation_db.clj, app/frontend/src/cljs/teet/common/common_controller.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_controller.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, ci/browser-tests/cypress/integration/cooperation.spec.js
Changed how adding 3rd party works to mach AC
=> TEET-1020 finalization

app/backend/resources/schema.edn, app/backend/src/clj/teet/cooperation/cooperation_commands.clj, app/common/src/cljc/teet/cooperation/cooperation_model.cljc
Adds a link to activity for cooperation applications.
=> TEET-615 adds link to activity for application

app/backend/nvd-lock.edn, app/backend/src/clj/teet/meeting/meeting_db.clj, app/backend/src/clj/teet/meeting/meeting_pdf.clj, app/backend/src/clj/teet/meeting/meeting_queries.clj, app/backend/src/clj/teet/project/project_db.clj, app/backend/test/teet/meeting/meeting_pdf_test.clj, app/frontend/src/cljs/teet/meeting/meeting_view.cljs, ci/browser-tests/README
1. add unit tests for Meeting pdf
2. fix Meeting pdf file name to the one containing the titlte
=> Teet 926 unit tests

app/backend/src/clj/teet/cooperation/cooperation_db.clj, app/frontend/src/cljs/teet/common/common_styles.cljs
ordering for applications fixed
=> teet-1022 fixes application ordering

app/backend/src/clj/teet/integration/x_road/business_registry.clj, app/backend/test/teet/land/land_queries_test.clj, app/frontend/src/cljs/teet/common/common_controller.cljs, app/frontend/src/cljs/teet/project/land_controller.cljs, app/frontend/src/cljs/teet/project/land_view.cljs, db/src/main/resources/db/migration/V19__Set_estate_fetched_at_on_update.sql
https://jira.mkm.ee/browse/TEET-798
=> TEET-798 Owner contact info query fails when an estate has many (41) owners

app/backend/nvd-lock.edn, app/backend/src/clj/teet/meeting/meeting_db.clj, app/backend/src/clj/teet/meeting/meeting_pdf.clj, app/backend/src/clj/teet/util/md.clj, app/backend/test/teet/meeting/meeting_pdf_test.clj
- do not show removed participants on PDF reports
- extend the Markdown parser with Underlined text support
=> Teet 926 minor bug fixes

app/backend/src/clj/teet/file/file_commands.clj, app/backend/test/teet/file/file_commands_test.clj
=> Teet-1013 fixes file replace when using a different extension

app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/file/file_tx.clj, app/backend/test/teet/file/file_commands_test.clj
Handle case where retracting attributes didn't check unique properly and add some tests
=> TEET-1058 mark2

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/dashboard/dashboard_view.cljs, app/frontend/src/cljs/teet/file/file_controller.cljs, app/frontend/src/cljs/teet/file/file_view.cljs, app/frontend/src/cljs/teet/task/task_view.cljs, app/frontend/src/cljs/teet/ui/buttons.cljs, app/frontend/src/cljs/teet/ui/form.cljs, app/frontend/src/cljs/teet/ui/panels.cljs, ci/browser-tests/cypress/fixtures/file.txt, ci/browser-tests/cypress/fixtures/text_file.jpg, ci/browser-tests/cypress/integration/login.spec.js, ci/browser-tests/cypress/integration/task.spec.js, ci/browser-tests/cypress/support/commands.js
PR changes file delete confirm dialog text, fixes version upload from file listing.
=> TEET-1027 Display a custom confirm message when deleting all versions of a file

app/backend/src/clj/teet/cooperation/cooperation_queries.clj, app/common/src/cljc/teet/cooperation/cooperation_model.cljc, app/frontend/src/cljs/teet/common/common_styles.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_controller.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/meeting/meeting_view.cljs, app/frontend/src/cljs/teet/ui/common.cljs, app/frontend/src/cljs/teet/ui/form.cljs, app/frontend/src/cljs/teet/ui/rich_text_editor.cljs, ci/browser-tests/cypress/integration/cooperation.spec.js
same as the earlier branch but unbungled the git commit order.
=> Teet 613 cooperation opinions

app/backend/src/clj/teet/task/task_db.clj, app/backend/test/teet/activity_commands_test.clj
THK elegibility test was returning false negatives when multiple tasks of same type were selected.
=> Fix and test for TEET-1040

app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/link/link_queries.clj, app/backend/src/clj/teet/task/task_db.clj
Fix searching only the latest vesrsion of the File description
=> TEET-991 bug fix

app/backend/src/clj/teet/admin/admin_queries.clj, app/frontend/src/cljs/teet/admin/admin_view.cljs, ci/browser-tests/cypress/integration/admin_inspector.spec.js
Add query and view in admin inspector that shows full tx log of the entity.
=> TEET-1094 support showing full tx history of entity

app/common/src/cljc/teet/cooperation/cooperation_model.cljc, app/common/src/cljc/teet/util/date.cljc
Fixes a minor issue with count until date being wrong
=> teet-613 fixes days until warning error

app/frontend/src/cljs/teet/project/land_controller.cljs, app/frontend/src/cljs/teet/project/land_view.cljs
Still needs testing in AWS env, worked ok in local dev env.
=> Revive retry-on-timeout logic for x-road estate info fetch (TEET-772)

app/frontend/src/cljs/teet/projects/projects_style.cljs, app/frontend/src/cljs/teet/projects/projects_view.cljs
What it says on the tin.
Pure layout change, so no accompanying tests.
=> TEET-1000 Fix project list filter layout

app/backend/src/clj/teet/cooperation/cooperation_commands.clj, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/ui/buttons.cljs, app/frontend/src/cljs/teet/ui/form.cljs, ci/browser-tests/package-lock.json, ci/browser-tests/package.json
=> TEET-611 application contact info

app/backend/resources/datomic/ion-config.edn, app/backend/src/clj/teet/activity/activity_commands.clj, app/backend/src/clj/teet/activity/activity_db.clj, app/backend/src/clj/teet/activity/activity_tx.clj, app/backend/src/clj/teet/task/task_db.clj, app/backend/test/teet/activity_commands_test.clj, app/backend/test/teet/comment_commands_test.clj, app/common/src/cljc/teet/activity/activity_model.cljc, app/frontend/src/cljs/teet/task/task_controller.cljs
Lots of fns moved to other namespaces. The main actual change is that the task creation now checks in the tx fn that the tasks aren't duplicated.
=> Teet 853 task uniqueness

app/frontend/src/cljs/teet/file/file_view.cljs, ci/browser-tests/cypress/integration/task.spec.js
Cypress task test was targeting wrong elements.
=> Fix task cypress test

app/backend/src/clj/teet/db_api/core.clj, app/backend/test/teet/meeting/meeting_commands_test.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn
Add a fallback string length enforcement to all tx-data.
=> TEET-1191 string length enforcement

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/ui/buttons.cljs, app/frontend/src/cljs/teet/ui/form.cljs
some minor tweaks to the cooperation based on demo.
=> Teet 1241 cooperation fixes

app/frontend/src/cljs/teet/map/map_view.cljs
I'll merge this one-liner with cosmetic change myself.
=> Fix map layer edit styles

app/backend/resources/asset-base-schema.edn, app/backend/resources/asset-schema.edn, app/backend/src/clj/teet/environment.clj, app/build-tools/deps.edn, app/build-tools/src/teet/asset_schema.clj
Generate asset schema from road object type library Excel.
=> TEET-1200 generate asset schema

app/backend/resources/asset-base-schema.edn, app/backend/resources/asset-schema.edn, app/backend/src/clj/teet/asset/asset_queries.clj, app/backend/src/clj/teet/db_api/db_api_handlers.clj, app/backend/src/clj/teet/environment.clj, app/build-tools/src/teet/asset_schema.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/resources/routes.edn, app/frontend/src/cljs/teet/asset/asset_library_view.cljs, app/frontend/src/cljs/teet/main.cljs, app/frontend/src/cljs/teet/navigation/navigation_view.cljs, app/frontend/src/cljs/teet/ui/common.cljs, app/frontend/src/cljs/teet/ui/icons.cljs, ci/browser-tests/browser-test-config.edn, ci/browser-tests/cypress/integration/rotl.ci.spec.js
New query and view for ROTL (road object type library).
Added very simple test (expecting more changes to the UI later).
=> TEET-1201 asset type library browser

app/backend/src/clj/teet/account/account_commands.clj, app/backend/src/clj/teet/account/account_queries.clj, app/backend/src/clj/teet/db_api/db_api_handlers.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/common/src/cljc/teet/user/user_spec.cljc, app/frontend/resources/routes.edn, app/frontend/src/cljs/teet/account/account_controller.cljs, app/frontend/src/cljs/teet/account/account_view.cljs, app/frontend/src/cljs/teet/main.cljs, app/frontend/src/cljs/teet/navigation/navigation_controller.cljs, app/frontend/src/cljs/teet/navigation/navigation_style.cljs, app/frontend/src/cljs/teet/navigation/navigation_view.cljs, app/frontend/src/cljs/teet/notification/notification_view.cljs, app/frontend/src/cljs/teet/theme/theme_colors.cljs, app/frontend/src/cljs/teet/ui/form.cljs, app/frontend/src/cljs/teet/ui/icons.cljs, app/frontend/src/cljs/teet/ui/material_ui.cljs, app/frontend/src/cljs/teet/ui/text_field.cljs, app/frontend/src/cljs/teet/ui/validation.cljs, ci/browser-tests/README, ci/browser-tests/cypress/integration/account.spec.js, ci/browser-tests/cypress/integration/login.spec.js, ci/browser-tests/cypress/integration/task.spec.js, ci/browser-tests/cypress/support/commands.js
New navigation element to get to the account page and a new page to edit account information.
=> Teet 1158 user page

app/backend/src/clj/teet/account/account_queries.clj
Adds person id to the query for account page
=> TEET-1158 adds person-id to the query of the

app/backend/src/clj/teet/integration/postgrest.clj
The PR logs PostgREST decode exceptions.
https://jira.mkm.ee/browse/TEET-1286
=> Log postgrest error

app/backend/deps.edn, app/backend/src/clj/teet/environment.clj, app/backend/src/clj/teet/integration/integration_email.clj, app/backend/test/teet/integration/integration_email_test.clj
Send emails via SMTP rather than AWS SES
=> Add dependency to SMTP lib

app/backend/src/clj/teet/cooperation/cooperation_db.clj, app/backend/src/clj/teet/cooperation/cooperation_queries.clj, app/frontend/src/cljs/teet/common/common_controller.cljs, app/frontend/src/cljs/teet/common/common_styles.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/login/login_controller.cljs, app/frontend/src/cljs/teet/map/map_controller.cljs, app/frontend/src/cljs/teet/ui/buttons.cljs, app/frontend/src/cljs/teet/ui/query.cljs, app/frontend/src/cljs/teet/ui/rich_text_editor.cljs, app/frontend/src/cljs/teet/ui/select.cljs, app/frontend/src/cljs/teet/ui/text_field.cljs, ci/browser-tests/cypress/integration/cooperation.ci.spec.js
Adds initial application filtering to cooperation view.
=> Teet 1277 filter applications

app/backend/src/clj/teet/meeting/meeting_pdf.clj
Update that handles the error due to missing language
=> TEET-1239 update

app/backend/src/clj/teet/db_api/db_api_large_text.clj
Make sure the saving works by checking the hash after it has been replaced.
=> TEET-1203 Add pre/post conditions for postgrest storage

app/backend/src/clj/teet/integration/integration_email.clj, app/backend/src/clj/teet/meeting/meeting_commands.clj, app/backend/test/teet/integration/integration_email_test.clj
Change composing the email message as described for Postal library
=> fix format of message for Postal SMTP library

app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs
Simply remove empty values from the form on send.
=> TEET-1311 clear empty values from cooperation application form

app/backend/src/clj/teet/cooperation/cooperation_commands.clj, app/backend/src/clj/teet/cooperation/cooperation_db.clj, app/backend/src/clj/teet/cooperation/cooperation_tx.clj, app/backend/test/cooperation/cooperation_commands_test.clj, app/common/src/cljc/teet/cooperation/cooperation_model.cljc, app/common/src/cljc/teet/util/datomic.cljc, app/frontend/src/cljs/teet/cooperation/cooperation_controller.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/ui/form.cljs, ci/browser-tests/cypress/integration/cooperation.ci.spec.js
This PR adds functionality for editing and deleting applications. Editing and deleting is only allowed if the application has not been given a third party response.
=> TEET-1261 As a user I want to edit and delete cooperation applications

app/backend/src/clj/teet/cooperation/cooperation_db.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/cooperation/cooperation_style.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/theme/theme_colors.cljs, app/frontend/src/cljs/teet/ui/typography.cljs
testing fixes for cooperation application views
=> Teet 620 testing fixes

app/backend/resources/datomic/ion-config.edn
PR adds two functions to ion config.
=> TEET-1261 Allow edit-application and delete-application in ion config

app/frontend/src/cljs/teet/login/login_view.cljs, app/frontend/src/cljs/teet/navigation/navigation_logo.cljs
Add default values for new logo width and height so it's visible in chrome
=> TEET-1216 fixes logo visibility in chrome

app/backend/src/clj/teet/environment.clj
This PR adds vektor.io config parsing from SSM params.
=> TEET-1273 Add vektor.io config parsing from SSM params

app/backend/src/clj/teet/meeting/meeting_pdf.clj
small change to fix the meeting pdf generation for large texts
=> TEET-1322 fixes meeting-pdf generation with large-text

ci/deploy/wait_for_datomic.bash
(also a test commit to ensure previous successful deploy wasn't a fluke)
=> Reduce CI script debug now that deploy prob was narrowed down

app/frontend/src/cljs/teet/meeting/meeting_view.cljs, app/frontend/src/cljs/teet/navigation/navigation_logo.cljs, app/frontend/src/cljs/teet/ui/form.cljs
A bit of rewriting required to manage the removal of the decision and agenda topic body when the editing form is active.
=> Teet 1338 meeting page bug

app/backend/resources/schema.edn, app/backend/src/clj/teet/file/file_commands.clj, app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/file/file_import.clj, app/backend/src/clj/teet/integration/vektorio/vektorio_client.clj, app/backend/src/clj/teet/integration/vektorio/vektorio_core.clj, app/common/src/cljc/teet/file/filename_metadata.cljc
First version of file uploads to vektorio when uploaded to teet.
=> Teet 1255 vektor mirror

app/backend/src/clj/teet/integration/vektorio/vektorio_core.clj
Fixed a bug with the vektorio integration
=> Fixes a bug in integration

app/backend/src/clj/teet/cooperation/cooperation_export.clj, app/common/src/cljc/teet/util/datomic.cljc
=> TEET-1004 too many results

app/backend/src/clj/teet/integration/vektorio/vektorio_client.clj, app/backend/src/clj/teet/integration/vektorio/vektorio_core.clj
remove api key from logs and add a bit logging as well
=> TEET-1255 vektorio logging changes

app/frontend/src/cljs/teet/app_state.cljs, app/frontend/src/cljs/teet/common/responsivity_styles.cljs, app/frontend/src/cljs/teet/navigation/navigation_controller.cljs, app/frontend/src/cljs/teet/navigation/navigation_logo.cljs, app/frontend/src/cljs/teet/navigation/navigation_style.cljs, app/frontend/src/cljs/teet/navigation/navigation_view.cljs, app/frontend/src/cljs/teet/notification/notification_view.cljs, app/frontend/src/cljs/teet/project/project_view.cljs, app/frontend/src/cljs/teet/search/search_view.cljs, app/frontend/src/cljs/teet/ui/common.cljs
First version of supporting mobiles in navigation elements
=> TEET-1172 adds support for mobile navigation

app/backend/src/clj/teet/cooperation/cooperation_db.clj
Previously it could find activities that are deleted.
=> TEET-1349 fixes cooperation application activity matching

app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/project/project_queries.clj, app/frontend/src/cljs/teet/activity/activity_view.cljs, app/frontend/src/cljs/teet/task/task_view.cljs, ci/browser-tests/cypress/integration/task_files.ci.spec.js
Only show menu item if there are files
=> TEET-936 fixes

README.md
This PR adds short instructions on what to do when adding a new feature flag to the codebase.
=> TEET-1329 Add instructions on feature flags to README

app/backend/src/clj/teet/comment/comment_commands.clj, app/frontend/dev.cljs.edn
=> Minor fixes

app/backend/src/clj/teet/file/file_commands.clj
=> TEET-1270 vektorio delete hook: handle files without associated projects 

app/frontend/src/cljs/teet/navigation/navigation_view.cljs
Fixes feedback email when not logged in.
=> TEET-1371 fixes feedback email

app/frontend/src/cljs/teet/navigation/navigation_style.cljs, app/frontend/src/cljs/teet/navigation/navigation_view.cljs, app/frontend/src/cljs/teet/ui/select.cljs
A small fix for the logged out view to have a globe icon instead of the text language.
=> TEET-1172 fixes language selector for logged out view

app/backend/src/clj/teet/backup/backup_ion.clj
to investigate issue, add error logging
=> TEET-1404 Add try/catch to generating backup zip

app/frontend/src/cljs/teet/main.cljs, app/frontend/src/cljs/teet/navigation/navigation_view.cljs
=> TEET-1371 pass proper url for feedback link in logged out view

app/backend/nvd-lock.edn, app/backend/src/clj/teet/file/file_db.clj, app/backend/src/clj/teet/file/file_import.clj
Need to manually catch and log exceptions when using `future`.
=> TEET-1269 add scheduled import logging

app/frontend/src/cljs/teet/asset/cost_items_view.cljs
Minor UX tuning and rerendering optimization. Works better on mobile now.
=> TEET-1364 Cost item form tuning

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/activity/activity_view.cljs, app/frontend/src/cljs/teet/common/common_styles.cljs, app/frontend/src/cljs/teet/project/project_navigator_view.cljs, app/frontend/src/cljs/teet/task/task_view.cljs, app/frontend/src/cljs/teet/theme/theme_provider.cljs, app/frontend/src/cljs/teet/ui/buttons.cljs, app/frontend/src/cljs/teet/ui/common.cljs, app/frontend/src/cljs/teet/ui/icons.cljs, app/frontend/src/cljs/teet/ui/panels.cljs
Fixes some stylings with the download related info dropdown.
=> Teet 936 download docs

app/backend/src/clj/teet/file/file_import.clj
Adds some extra spice to the logging of the scheduled vektorio upload runner
=> TEET-1255 adds some logging to the scheduled runner

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/project/land_view.cljs, app/frontend/src/cljs/teet/ui/panels.cljs
Link to new modal "Land owners opinions" added.
=> Add link to Owners opinions to Estate info

app/backend/resources/authorization.edn, app/backend/resources/schema.edn, app/backend/src/clj/teet/db_api/db_api_handlers.clj, app/backend/src/clj/teet/land/owner_opinion_commands.clj, app/backend/src/clj/teet/land/owner_opinion_db.clj, app/backend/src/clj/teet/land/owner_opinion_queries.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/common/src/cljc/teet/land/owner_opinion_specs.cljc, app/frontend/src/cljs/teet/dashboard/dashboard_view.cljs, app/frontend/src/cljs/teet/land/land_controller.cljs, app/frontend/src/cljs/teet/land/land_style.cljs, app/frontend/src/cljs/teet/land/land_view.cljs, app/frontend/src/cljs/teet/land/owner_opinion_controller.cljs, app/frontend/src/cljs/teet/land/owner_opinion_view.cljs, app/frontend/src/cljs/teet/project/project_setup_view.cljs, app/frontend/src/cljs/teet/project/project_view.cljs, app/frontend/src/cljs/teet/ui/panels.cljs
Most new stuff is related to land owner opinions which is hidden behind a feature flag in the frontend. Also refactored land section views to a better place and moved styles to a new ns.
=> Teet 1356 add opinion of land owner

app/backend/src/clj/teet/integration/vektorio/vektorio_client.clj
Force Vektor to use EPSG3301 coordinate system
=> Teet 1435 

app/frontend/src/cljs/teet/asset/cost_items_view.cljs
Remove unneeded key which blocked saving.
=> TEET-1432 Remove :ctype which is no longer needed

ci/browser-tests/cypress-localdev.json, ci/browser-tests/cypress/integration/land_section.spec.js, ci/browser-tests/package.json
This seemed to solve the problem when running it locally. Maybe there's a better option to open the main menu?
=> TEET-1398 hack for opening main menu

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/asset/cost_items_view.cljs, app/frontend/src/cljs/teet/theme/container_theme.cljs, app/frontend/src/cljs/teet/ui/container.cljs
Group fields in the form to separately collapsible sections (all open by default)
=> TEET-1420 Group fields

app/backend/nvd-lock.edn, app/backend/src/clj/teet/land/land_queries.clj, app/backend/src/clj/teet/land/owner_opinion_commands.clj, app/backend/src/clj/teet/land/owner_opinion_export.clj, app/backend/src/clj/teet/land/owner_opinion_queries.clj, app/backend/src/clj/teet/util/html_export.clj, app/backend/test/teet/integration/x_road_test.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/common/src/cljc/teet/project/project_model.cljc
html export for land owner opinions
=> Teet 1360 html export

app/backend/dev-src/user.clj, app/backend/nvd-lock.edn, app/backend/resources/asset-base-schema.edn, app/backend/src/clj/teet/asset/asset_commands.clj, app/backend/src/clj/teet/asset/asset_db.clj, app/backend/src/clj/teet/db_api/core.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/common/src/cljc/teet/asset/asset_type_library.cljc, app/common/src/cljc/teet/util/collection.cljc, app/frontend/src/cljs/teet/asset/cost_items_controller.cljs, app/frontend/src/cljs/teet/asset/cost_items_view.cljs, app/frontend/src/cljs/teet/common/common_styles.cljs, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs, app/frontend/src/cljs/teet/ui/breadcrumbs.cljs, app/frontend/src/cljs/teet/ui/query.cljs
Separate form for asset and component.
Components are listed under asset and can be navigated to.
=> TEET-1125 new design

app/backend/dev-src/teet/test_setup.clj, app/backend/src/clj/teet/land/owner_opinion_export.clj, app/backend/src/clj/teet/land/owner_opinion_queries.clj, app/backend/src/clj/teet/routes.clj, app/frontend/src/cljs/teet/land/owner_opinion_view.cljs, app/frontend/src/cljs/teet/project/project_menu.cljs, app/frontend/src/cljs/teet/project/project_view.cljs, ci/browser-tests/browser-test-config.edn, ci/browser-tests/cypress/integration/land_owner_opinion.ci.spec.js, ci/browser-tests/cypress/support/commands.js
Adds estate names to the estate rows if they exist, and cypress test for land owner opinion export
=> Teet 1366 show estate names in html

app/backend/src/clj/teet/cooperation/cooperation_export.clj
removes not wanted attributes from the export html
=> TEET-1454 remove un wanted status of opinion and response from html

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/asset/asset_library_view.cljs
ROTL viewer shows notice above component attribute list if the component type inherits location from parent.
=> TEET-1433 Show notice about inherited location

app/backend/src/clj/teet/cooperation/cooperation_export.clj, app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs
AC2 of 1456 add cellpadding to the table, and also fix the button placement
=> TEET-1454 adds cellpadding and fixes button placement

app/frontend/src/cljs/teet/land/owner_opinion_view.cljs
Add descending sort by created date.
=> teet-1357: Add descending sorting by creation date

app/backend/src/clj/teet/file/file_tx.clj, app/backend/src/clj/teet/task/task_db.clj, app/backend/test/teet/file/file_commands_test.clj
fixes duplicate file uploading
=> Teet 1461 duplicate file upload

app/backend/src/clj/teet/meeting/meeting_commands.clj, app/backend/src/clj/teet/meeting/meeting_db.clj
Fixes deleted participants being cloned when cloning.
=> TEET-1444 fixes deleted participants being cloned

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn
Leeni made some changes to translations
=> TEET-1023 translation update

app/backend/src/clj/teet/cooperation/cooperation_commands.clj, app/backend/src/clj/teet/cooperation/cooperation_db.clj, app/backend/test/teet/cooperation/cooperation_commands_test.clj
=> TEET-1369: check application date validity when editing application

app/frontend/src/cljs/teet/snackbar/snackbar_controller.cljs
increase default snackbar hide duration
=> increase default hide duration from 5s to 15s

app/frontend/src/cljs/teet/land/owner_opinion_view.cljs
Change the callbacks so, the clear status will be the last to avoid dirty state.
=> Clear the flag of add new opinion incase of Cancel

app/common/src/cljc/teet/project/project_model.cljc
Show projects with empty status the last in project list.
=> Teet 1483 sorting all projects bug

app/frontend/src/cljs/teet/asset/cost_items_controller.cljs, app/frontend/src/cljs/teet/asset/cost_items_view.cljs
Use the form state update functions that work for cost item and any subcomponent to update the location fields.
=> TEET-1484 Fix location saving for component

app/backend/resources/asset-schema.edn, app/backend/resources/datomic/ion-config.edn, app/backend/src/clj/teet/asset/asset_commands.clj, app/backend/src/clj/teet/asset/asset_db.clj, app/backend/src/clj/teet/asset/asset_queries.clj, app/backend/src/clj/teet/asset/asset_tx.clj, app/backend/src/clj/teet/environment.clj, app/build-tools/src/teet/asset_schema.clj, app/common/src/cljc/teet/asset/asset_model.cljc, app/frontend/resources/routes.edn, app/frontend/src/cljs/teet/asset/cost_items_controller.cljs, app/frontend/src/cljs/teet/asset/cost_items_view.cljs
Generate and use OID numbers to refer to assets and components.
=> TEET-1368 Asset/component OID

app/backend/resources/asset-schema.edn, app/backend/src/clj/teet/asset/asset_db.clj
Pull list item values as maps with :db/id and :db/ident (like they are returned from pull) so frontend can render them properly.
Update ROTL from Excel.
=> TEET-1466 listitem fix

app/backend/nvd-lock.edn, app/backend/src/clj/teet/asset/asset_boq.clj, app/backend/src/clj/teet/asset/asset_queries.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/common/src/cljc/teet/asset/asset_type_library.cljc, app/frontend/src/cljs/teet/asset/cost_items_view.cljs
Preliminary Bill of Quantities export functionality.
Does not contain versions selection or other export properties yet, as versioning and locking are not implemented yet in the cost items.
=> TEET-1320 boq export

app/backend/resources/asset-base-schema.edn, app/backend/resources/datomic/ion-config.edn, app/backend/src/clj/teet/asset/asset_commands.clj, app/backend/src/clj/teet/asset/asset_db.clj, app/backend/src/clj/teet/asset/asset_tx.clj, app/backend/src/clj/teet/db_api/db_api_handlers.clj, app/backend/src/clj/teet/system/system_queries.clj, app/backend/test/teet/asset/asset_commands_test.clj, app/backend/test/teet/system_test.clj, app/backend/test/teet/test/utils.clj, app/common/src/cljc/teet/asset/asset_model.cljc
Add BOQ version that can be locked with test that locked version actually prevents changes.
=> TEET-1308 version schema

.github/disabled-workflows/nvd.yml, app/backend/src/clj/teet/thk/thk_mapping.clj
Remove the procurement rows from the export to thk
=> TEET-1223 removes procurement mappings from project export and import

app/frontend/src/cljs/teet/asset/cost_items_view.cljs, app/frontend/src/cljs/teet/ui/context.cljs
Don't render form components when locked. Just show the values as text.
=> TEET-1308 readonly forms

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/asset/cost_items_view.cljs, app/frontend/src/cljs/teet/project/project_menu.cljs
PR fixes bugs in cost item form validation
=> TEET-1421 fixes

app/frontend/src/cljs/teet/asset/asset_library_view.cljs, app/frontend/src/cljs/teet/common/common_styles.cljs, app/frontend/src/cljs/teet/route_macros.clj, app/frontend/src/cljs/teet/ui/container.cljs, ci/browser-tests/cypress/integration/rotl.ci.spec.js
Make ROTL viewer 2 panels: left side navigates the hierarchy and right side shows details of clicked item.
=> TEET-1584 rotl viewer 2 panels

app/backend/src/clj/teet/contract/contract_db.clj, app/backend/test/teet/contract/contract_db_test.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn
=> TEET-1224 fixes edge cases in the contract status and adds tests

app/backend/resources/schema.edn
=> TEET-1650 contract parter schema starter

app/backend/resources/asset-schema.edn, app/backend/src/clj/teet/asset/asset_db.clj, app/build-tools/src/teet/asset_schema.clj, app/frontend/src/cljs/teet/asset/asset_library_view.cljs
PR adds attributes and list items for materials to asset type library view.
=> TEET-1627 Add material attributes and list items

app/backend/resources/asset-base-schema.edn, app/backend/resources/datomic/ion-config.edn, app/backend/src/clj/teet/asset/asset_db.clj, app/backend/src/clj/teet/asset/asset_road_registry_import.clj, app/backend/src/clj/teet/asset/asset_tx.clj, app/backend/src/clj/teet/util/geo.clj, app/common/src/cljc/teet/util/coerce.cljc, app/frontend/src/cljs/teet/asset/assets_view.cljs, app/frontend/src/cljs/teet/map/map_features.cljs, app/frontend/src/cljs/teet/ui/common.cljs, app/frontend/src/cljs/teet/ui/table.cljs
- a lambda for importing a specific asset type from road registry
- configuration for mapping culvert data in road registry WFS to TEET assets
=> TEET-1674 import culvert data from WFS

app/backend/src/clj/teet/asset/asset_queries.clj, app/frontend/src/cljs/teet/asset/asset_ui.cljs, app/frontend/src/cljs/teet/asset/assets_controller.cljs, app/frontend/src/cljs/teet/asset/assets_view.cljs, app/frontend/src/cljs/teet/map/map_layers.cljs, app/frontend/src/cljs/teet/ui/select.cljs
=> TEET-1691 search by status

app/backend/resources/datomic/ion-config.edn
This PR adds save-material to ion-config.edn.
=> TEET-1676 Add save-material to ion-config.edn

app/backend/src/clj/teet/db_api/db_api_handlers.clj, app/frontend/src/cljs/teet/common/common_controller.cljs
Show specific error message if specified in headers
=> Teet 1259 error message

app/frontend/src/cljs/teet/asset/cost_items_controller.cljs, app/frontend/src/cljs/teet/asset/cost_items_view.cljs
Allow filter (by db ident) and road query params to work simultaneously
=> Teet 1580 filter and road selection fix

app/frontend/src/cljs/teet/asset/cost_groups_view.cljs, app/frontend/src/cljs/teet/asset/materials_and_products_view.cljs, app/frontend/src/cljs/teet/route_macros.clj
This PR fixes cost group navigation by properly namespacing keyword.
=> TEET-1736 Cost items left side feature menu filter does not work

ci/backup-restore-test/buildspec.yml, ci/backup-restore-test/restore.bash
- Fix calling notification bash script with parameters
=> Teet 1643 add more exception info in log

app/frontend/src/cljs/teet/asset/assets_view.cljs
Fix road address chips:
- make container wrap so multiple roads are properly visible
- use the road start/end km if no values are specified
=> TEET-1694 road chip fix

app/frontend/src/cljs/teet/contract/contract_partners_view.cljs
adds button and selected partner name header.
=> TEET-1733: add edit partner button

app/frontend/src/cljs/teet/asset/assets_view.cljs, app/frontend/src/cljs/teet/common/common_styles.cljs, app/frontend/src/cljs/teet/theme/theme_colors.cljs
Desktop version. No mobile version yet.
=> TEET-1768 Map/table toggle and result count indicator

app/frontend/src/cljs/teet/asset/assets_view.cljs
- fix map key (to force rerender after resize)
- initially only show map (not table)
=> TEET-1768 fixes

app/backend/src/clj/teet/asset/asset_db.clj
Fix binding of component type in query.
=> TEET-1773 query fix

app/frontend/src/cljs/teet/asset/assets_controller.cljs, app/frontend/src/cljs/teet/asset/assets_view.cljs
Search immediately when changing the "search by" type to clear out old results.
Also add missing radius selection to mobile map.
=> TEET-1694 search on change

app/backend/src/clj/teet/notification/notification_ion.clj, app/backend/src/clj/teet/thk/thk_integration_ion.clj, app/frontend/src/cljs/teet/admin/admin_view.cljs, app/frontend/src/cljs/teet/ui/format.cljs
- show tx time with millisecond precision
- show other tx metadata if no user associated with tx (any background task or integration tx)
- fix tx metadata for THK import
- add tx metadata for background notify
=> TEET-1245/-1783 admin inspector tx info improvements

ci/browser-tests/cypress/integration/land_section.spec.js
Look for button with class project-menu instead of specific type of
button (IconButton).
=> TEET-1429 Fix cypress test land_section.spec.js

app/backend/resources/contract-authorization.edn, app/backend/resources/schema.edn, app/build-tools/src/clj/teet/contract_authorization.clj
Added a new role in db for subcontractor employee, and changed the mapping
=> TEET-1770 added a role to db for subcontractor employees

app/frontend/src/cljs/teet/navigation/navigation_view.cljs, app/frontend/src/cljs/teet/project/project_menu.cljs, app/frontend/src/cljs/teet/project/project_navigator_view.cljs, app/frontend/src/cljs/teet/project/project_view.cljs
Split project menu into mobile/desktop variants.
=> TEET-1429 Show full-width project menu for mobile

app/frontend/src/cljs/teet/contract/contracts_view.cljs
Also fix cosmetic lint warnings.
=> Add distinguishing id for search input to support browser tests

.github/workflows/test.yml, app/backend/src/clj/teet/asset/asset_commands.clj, app/backend/test/teet/asset/asset_commands_test.clj, app/backend/test/teet/test/utils.clj
=> TEET-1718 Update asset geometries when saving asset/component

app/backend/src/clj/teet/dashboard/dashboard_queries.clj, app/backend/src/clj/teet/notification/notification_db.clj
Missing decision about what to do for the appbar notifications badge
=> TEET-1742 Fetch all notifications for user's projects

app/backend/src/clj/teet/contract/contract_db.clj
Fixed Company - Partners query attributes using keys from Company model
=> Teet 1231 ta manager edit partners company info fix

ci/analytics-config-sync/buildspec.yml, ci/analytics-config-sync/sync.bash, ci/autodeploy/buildspec.yml
There's a corresponding MR in the AWS repo.
=> TEET-1781 - CodeBuild job datomic config sync

ci/backup-restore-test/backup.bash, ci/backup-restore-test/dbswitch.bash, ci/backup-restore-test/restore.bash
Fix lambda invocation to work with AWS CLI v2 
see: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binarypara
=> Set in format so that it works in AWS CLI v2

app/backend/src/clj/teet/contract/contract_commands.clj, app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/common/src/cljc/teet/contract/contract_spec.cljc, app/frontend/src/cljs/teet/contract/contract_partners_view.cljs, app/frontend/src/cljs/teet/ui/select.cljs, app/frontend/src/cljs/teet/ui/validation.cljs
Bug fixes: 
1) User can click on save without entering any values. Afer that user is taken back to the add person page and gets a server error. 
2) Person ID doesn't mark as mandatory 
3) E-mail is not marked as mandatory
=> TEET-1778 Add persons / TEET-1761 Edit persons bug fixes

app/common/src/cljc/teet/contract/contract_spec.cljc, app/frontend/src/cljs/teet/contract/contract_partners_view.cljs
Add Given and Family name as required to Edit person form. Change validation on Person ID and email so, it doesn't give error right after the form is open and nothing is entered.
=> TEET-1778-minor-bug-fixes

app/backend/src/clj/teet/contract/contract_db.clj, app/backend/src/clj/teet/contract/contract_queries.clj, ci/browser-tests/cypress/integration/contract_mm.ci.spec.js
The PR fixes the related contracts query.
=> TEET-1860 As any user I want to see related contracts (construction/owner's supervision) for a contract

app/common/src/cljc/teet/asset/asset_model.cljc, app/frontend/src/cljs/teet/asset/assets_view.cljs
Fixes sorting based on asset search result table columns.
=> TEET-1900 Asset manager- Asset sorting does not work for asset type, road address and status.

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/contract/contract_partners_view.cljs
User not found -> User not found or already added
=> TEET-1232 Change "User not found" message for contract partners view

app/common/resources/public/language/et.edn
Vale emaili aadress -> Vale e-posti aadress
=> TEET-1778 Update localization :invalid-email in et.edn

app/backend/src/clj/teet/contract/contract_commands.clj
- Check if employee has already logged in when adding as a new user
- Check if employee has already been added to the contract
=> TEET-1232 Adding new company employees to contract fixes

app/frontend/src/cljs/teet/contract/contracts_view.cljs
=> TEET-1893 contracts expand all fix

app/common/resources/public/language/en.edn, app/common/resources/public/language/et.edn, app/frontend/src/cljs/teet/contract/contract_partners_view.cljs, app/frontend/src/cljs/teet/contract/contract_style.cljs, app/frontend/src/cljs/teet/ui/common.cljs
- Padding to Key person files header
- Tooltips for key person icon
=> Add tooltip to key person icon and padding to key person files header

app/frontend/resources/public/index.html
Add https://*.transpordiamet.ee to Content-Security-Policy to support switching from mnt.ee to transpordiamet.ee in the future.
=> Add https://*.transpordiamet.ee to Content-Security-Policy

app/frontend/src/cljs/teet/contract/contract_partners_view.cljs
Hide search from business registry button when search is disabled
=> TEET-1991 Contract- Search button can not be used

app/backend/resources/contract-authorization.edn
Update contract authorizations
=> TEET-1993 Update Contract authorizations

app/frontend/src/cljs/teet/contract/contract_partners_view.cljs
Hide save button then there are no information about user selected or entered
=> TEET-1991-hide-save-button-then-no-user
