solita/mnt-teet

app/frontend/src/cljs/teet/common/common_controller.cljs
app/frontend/src/cljs/teet/snackbar/snackbar_controller.cljs

Handle JWT failures (session expiration) by redirecting to login page and showing a warning snackbar message.
Internal server errors show a generic error snackbar message.

Handle 401 and 500 errors on frontend

---

app/backend/deps.edn
app/backend/src/clj/teet/db_api/db_api_handlers.clj
app/backend/src/clj/teet/login/login_commands.clj
app/backend/src/clj/teet/project/project_geometry.clj
app/backend/src/clj/teet/routes.clj
app/backend/src/clj/teet/thk/thk_integration_ion.clj
app/common/src/clj/teet/auth/jwt_token.clj
app/common/src/cljc/teet/util/string.cljc
app/datasource-import/deps.edn
app/datasource-import/example-config.edn
app/datasource-import/src/teet/datasource_import/core.clj
app/datasource-import/src/teet/datasource_import/shp.clj
app/frontend/src/cljs/teet/localization.cljs
db/src/main/resources/db/migration/V9__feature.sql

Added a more generic way to store map datasources. The definition of a datasource (with information about how to fetch it) is in the `datasource` table. Features imported from a datasource are in `feature` table.
Added a tool to import a datasource's features using the PostgREST API. 
The periodical/automated running of datasource import, along with hash/changed checking is out of scope for this issue, but I added the required columns for that as well.

Tables and tool to import map data sources

---

app/frontend/src/cljs/teet/common/common_controller.cljs
app/frontend/src/cljs/teet/main.cljs
app/frontend/src/cljs/teet/user/user_controller.cljs

Based on Ville's idea from yesterday

Frontend version desync / deployment break detection: detect any change to versions, don't try to track git revisions

---

app/backend/src/clj/teet/integration/x_road/property_registry.clj
app/datasource-import/src/teet/datasource_import/core.clj
db/src/main/resources/db/migration/V14__feature_deleted_column.sql

This is done by checking which feature IDs have been previously
imported but are missing in newly imported SHP files.

Keep track of deleted status of geo features

---

app/backend/resources/schema.edn
app/backend/src/clj/teet/file/file_commands.clj
app/backend/src/clj/teet/file/file_db.clj
app/frontend/src/cljs/teet/file/file_controller.cljs

- Add `:file/upload-complete?` attribute
- Mark file upload as complete after the S3 PUT request is done
- Only return upload complete files in file listing query

Add :file/upload-complete? and only return completed files

---

app/backend/resources/datomic/ion-config.edn
app/backend/src/clj/teet/ags/ags_import.clj
app/backend/src/clj/teet/comment/comment_commands.clj
app/backend/src/clj/teet/file/file_commands.clj
app/backend/src/clj/teet/file/file_db.clj
app/backend/test/teet/comment_commands_test.clj
app/backend/test/teet/file/file_commands_test.clj
app/backend/test/teet/file/file_model_test.clj
app/common/src/cljc/teet/file/file_model.cljc
app/common/src/cljc/teet/file/file_spec.cljc
app/common/src/cljc/teet/task/task_spec.cljc
app/frontend/src/cljs/teet/file/file_view.cljs
app/frontend/src/cljs/teet/task/task_view.cljs
app/frontend/src/cljs/teet/ui/file_upload.cljs

This PR removes mime type handling from the codebase. File suffixes are used instead.

TEET-786 continued: Remove mime types

---

app/backend/resources/schema.edn
app/backend/src/clj/teet/file/file_commands.clj
app/backend/src/clj/teet/file/file_db.clj
app/backend/src/clj/teet/file/file_queries.clj
app/backend/src/clj/teet/meeting/meeting_commands.clj
app/backend/src/clj/teet/meeting/meeting_queries.clj
app/frontend/src/cljs/teet/file/file_controller.cljs
app/frontend/src/cljs/teet/file/file_view.cljs
app/frontend/src/cljs/teet/meeting/meeting_view.cljs
app/frontend/src/cljs/teet/ui/buttons.cljs

Add attachments to meeting agenda items.
Reviewers and organizer can upload new attachments, all participants can access them.

TEET-647 attachments to meeting agenda

---

app/backend/src/clj/teet/activity/activity_commands.clj
app/backend/src/clj/teet/thk/thk_import.clj
app/backend/src/clj/teet/thk/thk_mapping.clj
app/frontend/src/cljs/teet/link/link_view.cljs
app/frontend/src/cljs/teet/ui/select.cljs

Use only 64 bits in the UUID numbers as THK has column type int8.
Ids are created by secure random and checked against the current database that they are not in use.

TEET-878 smaller UUID numbers

---

app/backend/src/clj/teet/activity/activity_commands.clj
app/backend/src/clj/teet/admin/admin_commands.clj
app/backend/src/clj/teet/db_api/core.clj
app/backend/src/clj/teet/log.clj
app/backend/src/clj/teet/project/project_commands.clj

This PR adds the option to add audit logging to actions (that is, commands and queries) by adding `audit? true` to the action options. This results in the attempt to call the given action being logged into audit log.

TEET-722 Add audit? option to actions, audit log privilege granting commands

---

app/backend/src/clj/teet/backup/backup_ion.clj
app/backend/src/clj/teet/environment.clj
app/backend/src/clj/teet/meeting/meeting_commands.clj
app/backend/src/clj/teet/notification/notification_sender.clj
app/backend/test/teet/environment_test.clj
app/common/src/cljc/teet/util/collection.cljc

Fetch all SSM configuration in batches and reload it once a minute.
Change all direct AWS API calls to use the centralized config instead.

TEET-844 reload config

---

app/backend/resources/schema.edn
app/backend/src/clj/teet/activity/activity_commands.clj
app/backend/src/clj/teet/backup/backup_ion.clj
app/backend/src/clj/teet/integration/integration_id.clj
app/backend/src/clj/teet/migration/thk_integration_id.clj
app/backend/src/clj/teet/project/project_commands.clj
app/backend/src/clj/teet/project/project_db.clj
app/backend/src/clj/teet/project/project_geometry.clj
app/backend/src/clj/teet/project/project_queries.clj
app/backend/src/clj/teet/thk/thk_export.clj
app/backend/src/clj/teet/thk/thk_import.clj
app/backend/src/clj/teet/thk/thk_integration_ion.clj
app/backend/src/clj/teet/thk/thk_mapping.clj
app/backend/test/teet/thk/thk_import_test.clj
app/frontend/src/cljs/teet/map/map_layers.cljs
app/frontend/src/cljs/teet/project/project_controller.cljs
db/src/main/resources/db/migration/R__04_entity.sql
db/src/main/resources/db/migration/V17__remove_unused_rpc.sql

Create :integration/id for THK projects that can be used as stable id that doesn't need special handling when doing backup/restore.

TEET-905 use :integration/id for project geometries

---

app/backend/test/teet/file/file_model_test.clj
app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn
app/common/src/cljc/teet/file/file_model.cljc
app/frontend/src/cljs/teet/ui/file_upload.cljs

This PR is a part of a more investigative ticket TEET-967.
It adds validation preventing the upload of 0 size files in the frontend.

TEET-967 0 size files in production

---

app/backend/src/clj/teet/thk/thk_integration_ion.clj

Changed lambda processing to be processed in the background (like backup/restore).
The lambda doesn't have to wait for response, as it isn't used.
No tests, as we don't have lambda trigger tests.

TEET-1069 async processing of THK lambdas

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/cljs/teet/map/openlayers/kuvataso.cljs
app/frontend/src/cljs/teet/map/openlayers/mvt.cljs
app/frontend/src/cljs/teet/ui/component_demo.cljs
app/frontend/src/cljs/teet/ui/mentions.cljs
ci/browser-tests/cypress/integration/mentions.spec.js

Fixes bug in mentions input where editing an input whose initial value already contained a mention would cause the caret to jump to the end of the mention.
Added cypress test for mentions.

TEET-1071 Fix caret jumping when editing existing mentions input

---

app/backend/src/clj/teet/file/file_tx.clj
app/backend/test/teet/file/file_commands_test.clj

Task parts can't be deleted if they contain files.
This check also took into account files that have been replaced and the newer version placed to another part.
Change query to disregard replaced files and add test for this flow.

TEET-1047 Don't include old file versions when checking for task part emptiness

---

db/src/main/resources/db/migration/R__04_entity.sql
db/src/main/resources/db/migration/V17__remove_unused_rpc.sql

A function defn (replace_entity_ids) had been removed from the repeatable migrations, and a non-repeatable migration tried to drop it unconditionally. This errored, but changing the nr migration caused a checksum error.
Restore the function in a repeatable migration in placeholder form.

fix situation with conflicting repeatable/non-repeatable migrations & dropped functions

---

app/frontend/src/cljs/teet/meeting/meeting_view.cljs

TEET-1049 and TEET-1050 fixes.

TEET-1049 and TEET-1050: Approved meetings can now be duplicated and modal opens correctly

---

app/frontend/src/cljs/teet/ui/rich_text_editor.cljs

use mousedown instead of on-click so the editor doesn't lose focus.

TEET-959 fixes rich text editor toggling of inline-styles

---

app/backend/src/clj/teet/file/file_queries.clj

Fixes an issue with file descriptions causing spaces to convert to + characters, which in turn caused subsequent file upload to create a duplicate with + instead of space in the name.

TEET-1186 fixes file names changing spaces to "+"

---

app/backend/src/clj/teet/user/user_queries.clj

Adds a check to user search to not include deactivated users.

Teet-1163 fixes deactivated users being shown in user search

---

app/frontend/src/cljs/teet/main.cljs
app/frontend/src/cljs/teet/navigation/navigation_view.cljs

Due to how reagent decides when to re-render a component, the mailto was showing stale info earlier. Fix by passing the url as a parameter to the component, instead of directly reading it from the js environment.

fix stale url in feedback mailto link (TEET-1184)

---

app/backend/src/clj/teet/file/file_db.clj

This PR ensures that files of deleted tasks are not shown in the cadastral unit info dialog. It is no longer possible to delete tasks that have undeleted files. However, there are tasks deleted before the restriction that do contain files.
I didn't add any tests as it isn't possible to introduce the situation that this PR fixes without directly setting the task's `:meta/deleted?` attribute in the database.

TEET-1026 Only show sequence number files whose task has not been deleted

---

app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs
app/frontend/src/cljs/teet/ui/drag.cljs

File upload form being inside the authorization-context made it re-render on every form change, also if given id doesn't exist then the whole page went white, so using some-> instead of ->, indicates properly that no drop zone exists.

TEET-1162 fixes drop-zone issue in cooperation view

---

app/backend/src/clj/teet/cooperation/cooperation_db.clj
app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn

fixes issue where button is enabled but files can't be uploaded to the cooperation response becasue the task doesn't allow file uploading.

TEET-1162 check that files can be uploaded to cooperation task

---

app/backend/src/clj/teet/cooperation/cooperation_commands.clj
app/backend/src/clj/teet/cooperation/cooperation_queries.clj
app/backend/src/clj/teet/db_api/db_api_large_text.clj
app/backend/src/clj/teet/integration/integration_s3.clj
app/backend/src/clj/teet/meeting/meeting_commands.clj
app/backend/src/clj/teet/meeting/meeting_queries.clj
app/backend/src/clj/teet/project/project_queries.clj
app/backend/src/clj/teet/task/task_commands.clj
app/backend/src/clj/teet/util/hash.clj
app/backend/test/teet/db_api/db_api_large_text_test.clj
app/common/src/cljc/teet/cooperation/cooperation_model.cljc
app/common/src/cljc/teet/meeting/meeting_model.cljc
app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs
app/frontend/src/cljs/teet/meeting/meeting_view.cljs
app/frontend/src/cljs/teet/project/project_controller.cljs
app/frontend/src/cljs/teet/task/task_controller.cljs
app/frontend/src/cljs/teet/task/task_view.cljs
app/frontend/src/cljs/teet/ui/form.cljs
app/frontend/src/cljs/teet/ui/rich_text_editor.cljs
ci/browser-tests/cypress/integration/meeting.ci.spec.js
db/src/main/resources/db/migration/V20__large_text.sql

Add external storage of large tex in PostgreSQL.
Currently the functionality must be explicitly invoked in commands (to store externally) and queries (to fetch from external).
Also :task/description was changed to rich text field and the form refactored.

TEET-1203 large text support for rich text fields

---

app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs
app/frontend/src/cljs/teet/ui/query.cljs

change titles to match filter keys in cooperation search. And don't add filter key if the filter atom is empty.

TEET-620 minor changes for headings and when the query adds filters.

---

app/backend/src/clj/teet/thk/thk_import.clj
app/backend/test/teet/thk/thk_import_test.clj

This PR fixes THK import's project exclusion based on project group. The previous implementation checked `:object/groupname` whereas the proper field to check is `:thk.project/repair-method`. While at it, TEEMU projects were removed from exclusion list.

TEET-1317 Fix import exclusion, cease excluding TEEMU projects

---

app/backend/src/clj/teet/util/md.clj

When pasting stuff from HTML to the rich text editor, the content may include stuff that isn't normally creatable with the editor, like links and images.
Add basic support for those and escape text.

TEET-1323 pdf generation fixes

---

app/backend/src/clj/teet/db_api/db_api_dev.clj
app/backend/src/clj/teet/user/user_tx.clj
app/backend/test/teet/backup/backup_ion_test.clj
app/backend/test/teet/test/utils.clj
app/common/src/cljc/teet/util/datomic.cljc

Basically adds a wrapper to `d/q` that does extra validation against invalid calls to catch bugs easier.
Validates that all input parameters are referred to in the query and that the argument count matches the declared count)

Wrap Datomic q in with extra validations in local dev use and tests

---

app/frontend/src/cljs/teet/ui/rich_text_editor.cljs

Fix underlined section that ends in whitespace parsing problem. Hacky solution that just moves the whitespace after the underlined part.

TEET-1197 underlined with whitespace fix

---

app/backend/dev-src/user.clj
app/backend/src/clj/teet/meeting/meeting_db.clj
app/backend/src/clj/teet/meeting/meeting_pdf.clj
app/backend/src/clj/teet/meeting/meeting_queries.clj

Some pull queries had escaped attention when making the first PR to fix this.
As pull syntax doesn't support testing for absence of attributes, made a walk based filter for removing these as a postprocessing step.
Applied to both PDF generation queries and the regular meeting queries.

TEET-1243 part 2: filter incompete attachments in meeting queries

---

app/backend/src/clj/teet/backup/backup_ion.clj

Use `prn` instead of `pprint` as flame graph showed that printing large data structures was a bottleneck.
Also cache `:db/*` idents and only take the `as-of` db when necessary.

TEET-1334 fix slow backup

---

app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn

Adds localization for the case when user tries to send a zip to their email of the tasks files.

TEET-1478 adds localization for user-has-no-email error

---

app/frontend/src/cljs/teet/land/owner_opinion_controller.cljs
app/frontend/src/cljs/teet/land/owner_opinion_view.cljs
app/frontend/src/cljs/teet/ui/typography.cljs

- opinion author relationship with land is not in bold style as designed
- if the relationship empty the layout is still the same (place is taken even if empty)
- opinions list rows aligned to the left as designed
- update opinions count after delete

TEET-1357 and TEET-1358 fixes

---

app/backend/resources/authorization.edn
app/backend/src/clj/teet/cooperation/cooperation_commands.clj
app/backend/test/teet/cooperation/cooperation_commands_test.clj
app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs

Todo:
- ~~we're saving the :cooperation.response/status field in the save-application command which is equivalent to "approving the application" according to FR314. Need to control this according to the approve-application permission~~.
- application approval is no longer part of the workflow

TEET-1416: authz fix for ext consultants vs cooperation application

---

app/backend/src/clj/teet/integration/x_road/property_registry.clj
app/backend/src/clj/teet/land/land_queries.clj
ci/browser-tests/cypress/integration/land_section.spec.js

This PR fixes a bug where fetching cached xroad info occasionally fails due to a bug in rarely used codepath. It also prunes codepaths that end up making requests to xroad and removes unused code.

Fix fetching of xroad cache results

---

app/backend/src/clj/teet/thk/thk_import.clj
app/backend/src/clj/teet/thk/thk_mapping.clj

THK seems to change update timestamps every time it imports CSV from TEET. This causes every object to be "changed" when they send it back and causes unnecessary transaction growth on TEET side.
Don't store the THK update timestamps in integration info (send them back empty) as THK doesn't seem to use them.
Also sorts the integration info by keys so it is stable.

TEET-1509 don't store THK update timestamps

---

app/frontend/src/cljs/teet/project/project_setup_view.cljs
app/frontend/src/cljs/teet/project/project_view.cljs
app/frontend/src/cljs/teet/ui/panels.cljs

This PR fixes a bug which made it impossible to select cadastral units and restrictions by drawing the selected are on the map.
The fix replaces the use of `reagent.core/wrap` with the use of `reagent.core/cursor` and `reagent.ratom/make-reaction` to provide `panels/modal` with an atom-like object that behaves in the way we want.
One downside of the fix here is that `draw-selection` component now directly accesses the app state by constructing the cursor. However, all the events used from the `teet.project.project-controller` do the same.

TEET-1482 Unable to add cadastral units/restrictions by drawing a selection on the map

---

app/backend/nvd-lock.edn
app/backend/resources/asset-base-schema.edn
app/backend/src/clj/teet/asset/asset_db.clj
app/backend/src/clj/teet/asset/asset_queries.clj
app/backend/src/clj/teet/backup/backup_ion.clj
app/backend/src/clj/teet/environment.clj
app/backend/src/clj/teet/road/road_query_queries.clj
app/backend/src/clj/teet/road/teeregister_api.clj
app/backend/test/teet/test/utils.clj
app/common/src/cljc/teet/asset/asset_type_library.cljc
app/frontend/resources/routes.edn
app/frontend/src/cljs/teet/asset/cost_items_controller.cljs
app/frontend/src/cljs/teet/asset/cost_items_view.cljs
app/frontend/src/cljs/teet/common/common_controller.cljs
app/frontend/src/cljs/teet/map/map_features.cljs
app/frontend/src/cljs/teet/map/map_layers.cljs
app/frontend/src/cljs/teet/map/map_view.cljs
app/frontend/src/cljs/teet/map/openlayers.cljs
app/frontend/src/cljs/teet/map/openlayers/drag.cljs
app/frontend/src/cljs/teet/map/openlayers/geojson.cljs

Add selection of location for asset by clicking on map
One click takes a point geometry and second click turns it into a line geometry.
Fills in road address values (road, carriageway, start, end) and shows the geometry on the map.

TEET-1484 Asset location selection on map

---

app/backend/src/clj/teet/backup/backup_ion.clj
app/backend/test/teet/backup/backup_ion_test.clj

This PR changes the backup functionality so that empty transactions, i.e. transactions containing only metadata about the transaction itself, are not backed up.

TEET-1438 Backup/restore: skip empty transactions

---

app/backend/src/clj/teet/gis/entity_features.clj
app/backend/src/clj/teet/project/project_commands.clj
app/frontend/src/cljs/teet/project/search_area_controller.cljs

This PR fixes an issue where `:db/id` was used instead of `:integration/id` when adding search geometries.

TEET-1482 Use integration/id when adding search geometries

---

app/frontend/src/cljs/teet/asset/cost_items_controller.cljs
app/frontend/src/cljs/teet/routes.cljs

When navigating away from add component form, cleanup the app state.

Cancel component add fix

---

app/backend/resources/authorization.edn
app/backend/src/clj/teet/cooperation/cooperation_commands.clj
app/frontend/src/cljs/teet/cooperation/cooperation_view.cljs

This PR fixes the opinion authorization to work as follows:
- Only TA people (admin, manager, internal consultant) can add, edit and delete application opinions

TEET-1416 Fix authorization of opinion edits and deletes

---

app/backend/src/clj/teet/asset/asset_db.clj
app/backend/src/clj/teet/asset/asset_queries.clj
app/backend/src/clj/teet/db_api/core.clj
app/backend/src/clj/teet/db_api/db_api_handlers.clj
app/backend/src/clj/teet/transit.clj
app/frontend/resources/routes.edn
app/frontend/src/cljs/teet/asset/asset_library_view.cljs
app/frontend/src/cljs/teet/asset/cost_items_controller.cljs
app/frontend/src/cljs/teet/asset/cost_items_view.cljs

Asset type library is a large payload (146kb at this time and growing with time). Separate that to another query and fetch it only once when navigating to any view that needs it.
Query for relevant roads of a project uses external WFS service that may take a long time (depending on road length of project). Fetch that on demand for the project as needed and only once.

TEET-1616 separate ATL and WFS queries

---

app/backend/src/clj/teet/file/file_export.clj
app/backend/test/teet/file/file_export_test.clj

Activity export was fixed earlier. This PR adds duplicate file name renaming to task export. This is needed because earlier, duplicate filenames in one task were allowed, and such tasks exist in production.

TEET-1479 Handle duplicate files in export zip

---

app/frontend/src/cljs/teet/asset/cost_items_view.cljs

Use the same search input for fgroup/fclass selection on mobile as on desktop.

TEET-1630 Remove 2 pulldown mobile version, the search is better

---

app/frontend/src/cljs/teet/contract/contract_view.cljs

fix to use translation instead of enum value.

TEET-1227 fix hard coded activity name in the contract target listing

---

app/backend/src/clj/teet/asset/asset_db.clj
app/backend/src/clj/teet/asset/asset_queries.clj
app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn
app/frontend/resources/routes.edn
app/frontend/src/cljs/teet/asset/cost_items_view.cljs

Add "no road reference" option. "All roads" will only include assets that have a road (no matter what it is), "no road reference" includes only assets that are missing a road nr.

TEET-1580 no road reference

---

app/backend/src/clj/teet/asset/asset_commands.clj
app/backend/src/clj/teet/db_api/core.clj
app/common/src/cljc/teet/util/euro.cljc
app/frontend/src/cljs/teet/asset/cost_items_controller.cljs
app/frontend/src/cljs/teet/asset/cost_items_view.cljs
app/frontend/src/cljs/teet/ui/common.cljs

This PR implements the following fixes and improvements:
- Handle empty input by removing the price information
- Properly format field value after successful update
- Disable negative values for prices
- Set scale of prices to 2 decimal places, as Datomic strongly recommends having the same scale for all values of a given attribute.
- Fix case where price couldn't be updated back to previous value
- Fix case where text field remained disabled after attempting to input invalid price
- Fix case where text field remained disabled after successful update
- Fix case where inputting more than 2 decimal numbers results in updates failing due to failed CAS

TEET-1625 Cost item totals: price edit bug "server error"

---

app/backend/src/clj/teet/environment.clj
app/backend/src/clj/teet/login/login_commands.clj

Implement queries for Procurement State registry and THK links as configuration SSM parameters are not available in frontend.

Fix external links to Procurement registries

---

app/common/src/cljc/teet/util/coerce.cljc
app/common/src/cljc/teet/util/euro.cljc

This PR fixes bigdec parsing so that it survives whitespace between digits.

TEET-1688 Server error setting cost group price

---

app/backend/dev-src/user.clj
app/backend/resources/asset-base-schema.edn
app/backend/resources/asset-schema.edn
app/backend/src/clj/teet/asset/asset_commands.clj
app/backend/src/clj/teet/asset/asset_db.clj
app/backend/src/clj/teet/asset/asset_queries.clj
app/backend/src/clj/teet/asset/asset_tx.clj
app/build-tools/src/teet/asset_schema.clj
app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn
app/common/src/cljc/teet/asset/asset_model.cljc
app/common/src/cljc/teet/asset/asset_type_library.cljc
app/frontend/src/cljs/teet/asset/cost_items_controller.cljs
app/frontend/src/cljs/teet/asset/cost_items_view.cljs

This PR implements the basic CRUD operations for materials. Materials can only for components that are leafs in the asset type hierarchy.
What's _not_ implemented:
- Cost group functionality for materials
- Adding materials with no attributes (I assume this there are none as they get specified)

TEET-1676 Initial implementation: Adding materials or products to assets (cost items) 

---

app/frontend/src/cljs/teet/asset/cost_items_view.cljs

This PR fixes a bug where certain component options weren't passed recursively to subcomponent.

TEET-1676 Pass options recursively to subcomponent

---

app/common/src/cljc/teet/util/coerce.cljc

This PR adds back the \h separator that seemed useless.

TEET-1688 Remove separator space from fromatted numbers when parsing

---

app/backend/README.md
app/frontend/README.md
docs/dev-env/dev-env-mac.md

Update dev-env-mac.md
- Content changes
- Add step "Skip migration V17"
- Start Postgrest after devdb_clean, not before
- Add "Install postgrest" step
- Add reference to frontend README
- Remove section about Windows/WSL
- Fix some typos
- Formatting changes
- Use unordered lists, so that it is easier to add a new step in between
- Add code blocks to various places
Add mention about docs/dev-env to backend/README.md
Add login instructions to frontend README

Readme changes

---

ci/browser-tests/cypress/support/commands.js

This PR will increase the Cypress login timeout to 30 seconds.

Increase Cypress login timeout to prevent flaky tests

---

app/backend/README.md
app/backend/dev-src/user.clj
docs/dev-env/dev-env-mac.md

- Add steps for importing cloud database to backend/README.md
- Remove deprecated section "Connecting to Datomic locally"

README: import cloud db

---

app/backend/src/clj/teet/asset/asset_db.clj
app/frontend/src/cljs/teet/asset/cost_items_controller.cljs
app/frontend/src/cljs/teet/asset/materials_and_products_view.cljs

This PR
- removes subheadings from materials and products page
- doesn't group materials by feature groups and classes any more
- retains filtering by feature groups and classes

TEET-1712 Material grouping

---

app/frontend/src/cljs/teet/ui/select.cljs
app/frontend/src/cljs/teet/ui/text_field.cljs

Improve the input button styling so content doesn't show through it.
Handle stale result if an earlier input's result comes after a later one.

TEET-1694 minor select fixes

---

app/backend/README.md
db/README.md
docs/dev-env/dev-env-mac.md

- Remove note about bug in update-project-geometries (fixed now)
- Add section about how to run flyway migrations for existing database
- Add step to repair flyway checksum for skipped migration

Readme changes 2

---

app/frontend/src/cljs/teet/asset/cost_items_view.cljs
app/frontend/src/cljs/teet/ui/common.cljs
app/frontend/src/cljs/teet/ui/component_demo.cljs
app/frontend/src/cljs/teet/ui/date_picker.cljs
app/frontend/src/cljs/teet/ui/select.cljs
app/frontend/src/cljs/teet/ui/text_field.cljs

- Add option to show error as tooltip instead of label for `TextField`, `form-select` and `date-input`
- Show error message tooltips for cost-item attributes grid, so that input elements in the grid will stay aligned

TEET-1603: error tooltip

---

app/frontend/src/cljs/teet/asset/cost_items_view.cljs
app/frontend/src/cljs/teet/project/project_menu.cljs

- Change "Activities" to "Cost items" in the tab selector of Materials and products view
- Don't show "Components", ie. the empty component tree if the component has materials

Material fixes

---

app/frontend/src/cljs/teet/ui/common.cljs
app/frontend/src/cljs/teet/ui/select.cljs
app/frontend/src/cljs/teet/ui/text_field.cljs

Show error popup when the field is focused, even when not hovering.

TEET-1603 Show popup when focused

---

app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn
app/frontend/src/cljs/teet/project/project_menu.cljs
app/frontend/src/cljs/teet/project/project_navigator_view.cljs
app/frontend/src/cljs/teet/project/project_view.cljs

- Split project-menu into project-tab-header and project-menu
- Change IconButton to button-primary with icon and text
- Always use day theme for project menu because of the new location

TEET-1429 Move project menu next to project name

---

app/common/resources/public/language/en.edn
app/common/resources/public/language/et.edn
app/common/src/cljc/teet/util/collection.cljc
app/frontend/src/cljs/teet/common/common_styles.cljs
app/frontend/src/cljs/teet/main.cljs
app/frontend/src/cljs/teet/navigation/navigation_style.cljs
app/frontend/src/cljs/teet/navigation/navigation_view.cljs
app/frontend/src/cljs/teet/project/project_controller.cljs
app/frontend/src/cljs/teet/project/project_menu.cljs
app/frontend/src/cljs/teet/project/project_navigator_view.cljs
app/frontend/src/cljs/teet/project/project_view.cljs
app/frontend/src/cljs/teet/ui/buttons.cljs
app/frontend/src/cljs/teet/ui/hotkeys.cljs
ci/browser-tests/cypress/integration/cooperation.ci.spec.js
ci/browser-tests/cypress/integration/land_owner_opinion.ci.spec.js
ci/browser-tests/cypress/integration/land_section.spec.js
ci/browser-tests/cypress/integration/task.ci.spec.js
ci/browser-tests/cypress/support/commands.js

- Add extra header in app bar for project views on mobile
- Extra header contains project name and project menu
- Project name and menu are not shown in page content for mobile
- Remove hotkey handler by identity instead of popping

TEET-1429 project menu mobile

---

app/frontend/src/cljs/teet/contract/contract_view.cljs

This PR wraps the button inside a `when-authorized` component.

TEET-1857 Contracts edit- Unauthorized users should not see "Edit" button

---

app/backend/src/clj/teet/login/login_commands.clj

This PR prevents the login command from transacting to db if `dummy-login` is not enabled.

Have login command do nothing unless dummy login is enabled

---

app/frontend/src/cljs/teet/navigation/navigation_style.cljs
app/frontend/src/cljs/teet/ui/buttons.cljs

- Add z-index only to first appbar, so that second appbar will not be on top of quick search or other extra-panels
- Add box-shadow for last appbar, and border-bottom for others, so that UI looks more like Figma design

TEET-1429 search field visibility fix

---

app/frontend/src/cljs/teet/contract/contract_partners_view.cljs

Do not pass the whole app state into add-personnel-form, so that the form is not re-rendered when :extra-panel-open? changes.

TEET-1933 Fix "Add person view is closed when clicked on profile icon"

---

app/frontend/src/cljs/teet/contract/contract_partners_view.cljs

Fix routing to assign key person details view from Edit Employee form (after Cancel or Save buttons)

Fix routing to assign key person after person edit

---

app/backend/src/clj/teet/contract/contract_commands.clj
app/backend/src/clj/teet/user/user_db.clj

The bug was due to phone number not being fetched from db when comparing sent update to existing data.

TEET-1961 Contracts/Partner- Can not edit persons roles for one user
